-- VARIABLES TIPO TABLA
USE ADVENTUREWORKS2019 
-------------------------------------------------
--   PRUEBA 1 
-------------------------------------------------
DECLARE @T AS TABLE ([NAME]  VARCHAR(255),
                     [OBJECT_ID] INT,
					 [SCHEMA_ID]  INT,
					 [TYPE_DESC] VARCHAR(255),
					 [CREATE_DATE] DATETIME
					 )
					 
INSERT INTO @T 
SELECT TOP 100 
       NAME,
       OBJECT_ID,
	   SCHEMA_ID,
	   TYPE_DESC,
	   CREATE_DATE
FROM SYS.OBJECTS 

-- MIRAMOS TEMPDB

SELECT
        NAME,
        PS.INDEX_ID,
        PS.ROW_COUNT,
		(PS.USED_PAGE_COUNT * 8.00)/1024.00 AS ESPACIO_MB,
	    CREATE_DATE,
        MODIFY_DATE
    FROM TEMPDB.SYS.OBJECTS AS SO
    JOIN TEMPDB.SYS.DM_DB_PARTITION_STATS PS ON SO.OBJECT_ID = PS.OBJECT_ID
    WHERE
        NAME LIKE N'#%'
        AND ROW_COUNT > 0
GO

-- PRUEBA CON TABLA TEMPORAL
DROP TABLE IF EXISTS #TEMP1 

CREATE TABLE #TEMP1 ([NAME]  VARCHAR(255),
                     [OBJECT_ID] INT,
					 [SCHEMA_ID]  INT,
					 [TYPE_DESC] VARCHAR(255),
					 [CREATE_DATE] DATETIME
					 )


INSERT INTO #TEMP1  
SELECT TOP 100 
       NAME,
       OBJECT_ID,
	   SCHEMA_ID,
	   TYPE_DESC,
	   CREATE_DATE
FROM SYS.OBJECTS 



-- MIRAMOS TEMPDB

SELECT
        NAME,
        PS.INDEX_ID,
        PS.ROW_COUNT,
		(PS.USED_PAGE_COUNT * 8.00)/1024.00 AS ESPACIO_MB,
	    CREATE_DATE,
        MODIFY_DATE
    FROM TEMPDB.SYS.OBJECTS AS SO
    JOIN TEMPDB.SYS.DM_DB_PARTITION_STATS PS ON SO.OBJECT_ID = PS.OBJECT_ID
    WHERE
        NAME LIKE N'#%'
        AND ROW_COUNT > 0
GO

----------------------------------------------------------
--- PRUEBA 2: TABLAS MAS GRANDES -------------------------
----------------------------------------------------------
DROP TABLE IF EXISTS  #TEMP1 

CREATE TABLE #TEMP1 ([NAME]  VARCHAR(255),
                     [OBJECT_ID] INT,
					 [SCHEMA_ID]  INT,
					 [TYPE_DESC] VARCHAR(255),
					 [CREATE_DATE] DATETIME
					 )



DECLARE @T AS TABLE ([NAME]  VARCHAR(255),
                     [OBJECT_ID] INT,
					 [SCHEMA_ID]  INT,
					 [TYPE_DESC] VARCHAR(255),
					 [CREATE_DATE] DATETIME
					 )
					 
INSERT INTO @T 
SELECT TOP 5000000 
       O.NAME,
       O.OBJECT_ID,
	   O.SCHEMA_ID,
	   O.TYPE_DESC,
	   O.CREATE_DATE
FROM SYS.OBJECTS O 
CROSS JOIN SYS.COLUMNS C1
CROSS JOIN SYS.COLUMNS C2

-- MIRAMOS TEMPDB

SELECT
        NAME,
        PS.INDEX_ID,
        PS.ROW_COUNT,
		(PS.USED_PAGE_COUNT * 8.00)/1024.00 AS ESPACIO_MB,
	    CREATE_DATE,
        MODIFY_DATE
    FROM TEMPDB.SYS.OBJECTS AS SO
    JOIN TEMPDB.SYS.DM_DB_PARTITION_STATS PS ON SO.OBJECT_ID = PS.OBJECT_ID
    WHERE
        NAME LIKE N'#%'
        AND ROW_COUNT > 0
GO

-- PRUEBA CON TABLA TEMPORAL

INSERT INTO #TEMP1 
SELECT TOP 5000000 
       O.NAME,
       O.OBJECT_ID,
	   O.SCHEMA_ID,
	   O.TYPE_DESC,
	   O.CREATE_DATE
FROM SYS.OBJECTS O 
CROSS JOIN SYS.COLUMNS C1
CROSS JOIN SYS.COLUMNS C2

-- MIRAMOS TEMPDB

SELECT
        NAME,
        PS.INDEX_ID,
        PS.ROW_COUNT,
		(PS.USED_PAGE_COUNT * 8.00)/1024.00 AS ESPACIO_MB,
	    CREATE_DATE,
        MODIFY_DATE
    FROM TEMPDB.SYS.OBJECTS AS SO
    JOIN TEMPDB.SYS.DM_DB_PARTITION_STATS PS ON SO.OBJECT_ID = PS.OBJECT_ID
    WHERE
        NAME LIKE N'#%'
        AND ROW_COUNT > 0
GO

----------------------------------------
--- TABLAS REALES EN MEMORIA
----------------------------------------

-- IN MEMORY OLTP

ALTER DATABASE 
[AdventureWorks2019] 
ADD FILEGROUP [INMEM1] CONTAINS MEMORY_OPTIMIZED_DATA 

USE [master]
GO
ALTER DATABASE [AdventureWorks2019] 
ADD FILE ( NAME = N'INMEM2', 
FILENAME = N'F:\SQL\INMEM2' ) 
TO FILEGROUP [INMEM1]
GO

USE AdventureWorks2019 

CREATE TYPE dbo.inMemoryTableType  
  AS TABLE 
  (
    [NAME]  VARCHAR(255) INDEX IX1,
    [OBJECT_ID] INT,
	[SCHEMA_ID]  INT,
	[TYPE_DESC] VARCHAR(255),
    [CREATE_DATE] DATETIME
  
  )
  WITH (MEMORY_OPTIMIZED = ON);  
GO


DECLARE @T AS  dbo.inMemoryTableType  
INSERT INTO @T
SELECT TOP 100
       O.NAME,
       O.OBJECT_ID,
	   O.SCHEMA_ID,
	   O.TYPE_DESC,
	   O.CREATE_DATE
FROM SYS.OBJECTS O 


-- MIRAMOS TEMPDB

SELECT
        NAME,
        PS.INDEX_ID,
        PS.ROW_COUNT,
		(PS.USED_PAGE_COUNT * 8.00)/1024.00 AS ESPACIO_MB,
	    CREATE_DATE,
        MODIFY_DATE
    FROM TEMPDB.SYS.OBJECTS AS SO
    JOIN TEMPDB.SYS.DM_DB_PARTITION_STATS PS ON SO.OBJECT_ID = PS.OBJECT_ID
    WHERE
        NAME LIKE N'#%'
        AND ROW_COUNT > 0

-------------------------------------------------------------
-------------------  PRUEBA DE PERFORMANCE  -----------------
-------------------------------------------------------------

CREATE OR ALTER PROC USP_VARTABLE
AS
BEGIN
SET NOCOUNT ON
 DECLARE @T AS TABLE ([NAME]  VARCHAR(255),
                     [OBJECT_ID] INT,
					 [SCHEMA_ID]  INT,
					 [TYPE_DESC] VARCHAR(255),
					 [CREATE_DATE] DATETIME
					 )
					 
 INSERT INTO @T 
 SELECT TOP 100000 
       O.NAME,
       O.OBJECT_ID,
	   O.SCHEMA_ID,
	   O.TYPE_DESC,
	   O.CREATE_DATE
 FROM SYS.OBJECTS O 
 CROSS JOIN SYS.COLUMNS C1

  SELECT NAME FROM @T 
END

GO

CREATE OR ALTER PROC USP_TEMPTABLE
AS
BEGIN
SET NOCOUNT ON
 CREATE TABLE #T    ([NAME]  VARCHAR(255),
                     [OBJECT_ID] INT,
					 [SCHEMA_ID]  INT,
					 [TYPE_DESC] VARCHAR(255),
					 [CREATE_DATE] DATETIME
					 )
					 
 INSERT INTO #T 
 SELECT TOP 100000 
       O.NAME,
       O.OBJECT_ID,
	   O.SCHEMA_ID,
	   O.TYPE_DESC,
	   O.CREATE_DATE
 FROM SYS.OBJECTS O 
 CROSS JOIN SYS.COLUMNS C1

  SELECT NAME FROM #T 
END
GO


CREATE OR ALTER PROC USP_INMEM
AS
BEGIN
 SET NOCOUNT ON
 DECLARE @T AS dbo.inMemoryTableType  

 INSERT INTO @T 
 SELECT TOP 100000 
       O.NAME,
       O.OBJECT_ID,
	   O.SCHEMA_ID,
	   O.TYPE_DESC,
	   O.CREATE_DATE
 FROM SYS.OBJECTS O 
 CROSS JOIN SYS.COLUMNS C1

  SELECT NAME FROM @T 
END

GO
--USAMOS QUERY STRESS PARA PROBAR
EXEC DBO.USP_VARTABLE
EXEC DBO.USP_TEMPTABLE
EXEC DBO.USP_INMEM





