USE ADVENTUREWORKS2019 
GO

SP_HELPINDEX 'PRODUCTION.WORKORDER'

SELECT * 
FROM PRODUCTION.WORKORDER

SELECT * FROM PRODUCTION.WORKORDER
ORDER BY ORDERQTY 

SELECT * 
FROM PRODUCTION.WORKORDER
ORDER BY WORKORDERID 


SELECT TOP(1000) * FROM PRODUCTION.WORKORDER

SELECT TOP(1000) * FROM PRODUCTION.WORKORDER
ORDER BY ORDERQTY 

CREATE INDEX IX1 ON PRODUCTION.WORKORDER(ORDERQTY)

SELECT TOP(1000) * 
FROM PRODUCTION.WORKORDER

SELECT TOP(1000) * FROM PRODUCTION.WORKORDER
ORDER BY ORDERQTY 

SELECT * FROM PRODUCTION.WORKORDER
ORDER BY ORDERQTY 

SELECT * FROM PRODUCTION.WORKORDER
ORDER BY WORKORDERID 


DROP INDEX IX1 ON PRODUCTION.WORKORDER