------- ------------------------------------------
-------   SEQUENCE (2012)
---------------------------------------------------

/*
 CREATE SEQUENCE [SCHEMA_NAME . ] SEQUENCE_NAME
    [ AS [ BUILT_IN_INTEGER_TYPE | USER-DEFINED_INTEGER_TYPE ] ]
    [ START WITH <CONSTANT> ]
    [ INCREMENT BY <CONSTANT> ]
    [ { MINVALUE [ <CONSTANT> ] } | { NO MINVALUE } ]
    [ { MAXVALUE [ <CONSTANT> ] } | { NO MAXVALUE } ]
    [ CYCLE | { NO CYCLE } ]
    [ { CACHE [ <CONSTANT> ] } | { NO CACHE } ]
    [ ; ]
*/


USE TEMPDB 
GO

CREATE SEQUENCE DBO.ORDERIDS AS INT    
MINVALUE 1    
NO MAXVALUE    
START WITH 1;

SET NOCOUNT ON;

SELECT NEXTORDERID = NEXT VALUE FOR DBO.ORDERIDS 


ALTER SEQUENCE DBO.ORDERIDS    
RESTART WITH 20;
SET NOCOUNT ON;

SELECT NEXTORDERID = NEXT VALUE FOR DBO.ORDERIDS

--- CONTROL TRANSACCIONAL

BEGIN TRANSACTION;    
 SELECT NEXTBAR = NEXT VALUE FOR DBO.ORDERIDS;
  ROLLBACK TRANSACTION;
SELECT NEXTBAR = NEXT VALUE FOR DBO.ORDERIDS;

-- SEQ NEGATIVA

CREATE SEQUENCE DBO.PO    AS INT    
START WITH 0
INCREMENT BY -1;

SET NOCOUNT ON;

SELECT NEXTORDERID = NEXT VALUE FOR DBO.PO 

------------------------ TABLAS CON SECUENCIAS

CREATE SEQUENCE DBO.NUMERO AS INT
MINVALUE 1    
NO MAXVALUE    
START WITH 1;

CREATE TABLE DBO.FACTURAS (ID INT DEFAULT (NEXT VALUE FOR DBO.NUMERO),
                           FECHA DATE
						   )

INSERT INTO DBO.FACTURAS (FECHA) VALUES (GETDATE())
INSERT INTO DBO.FACTURAS (FECHA) VALUES (GETDATE()+1)

SELECT * FROM DBO.FACTURAS 

INSERT INTO DBO.FACTURAS (id,FECHA) VALUES (10,GETDATE()+1)

-------- CYCLE

CREATE SEQUENCE DBO.NUMERO2 AS INT
MINVALUE 1    
MAXVALUE 10   
START WITH 1
CYCLE;

SELECT NEXT VALUE FOR DBO.NUMERO2
GO 20


------------------------------------------- NEXT VALUE
------------------------------------------------------
USE TEMPDB
GO

CREATE SCHEMA TEST;
GO

CREATE SEQUENCE TEST.COUNTBY1
    START WITH 1
    INCREMENT BY 1 ;
GO
--USING THE NEXT VALUE FOR FUNCTION WITH SELECT … INTO
SELECT NEXT VALUE FOR TEST.COUNTBY1 AS LOCNUMBER, NAME 
    INTO #NEWLOCATION
    FROM AdventureWorks2014.Production.LOCATION ;
GO

SELECT * FROM #NEWLOCATION ;
GO

--USING THE NEXT VALUE FOR FUNCTION IN AN INSERT STATEMENT

CREATE TABLE TEST.TESTTABLE
     (COUNTERCOLUMN INT PRIMARY KEY,
      NAME NVARCHAR(25) NOT NULL) ; 
GO

INSERT TEST.TESTTABLE (COUNTERCOLUMN,NAME)
    VALUES (NEXT VALUE FOR TEST.COUNTBY1, 'SYED') ;
GO

SELECT * FROM TEST.TESTTABLE; 
GO


--- GRANTING PERMISSION TO EXECUTE NEXT VALUE FOR

GRANT UPDATE ON OBJECT::TEST.COUNTERSEQ TO [ADVENTUREWORKS\LARRY] ;
