/*
 Mantenimiento de indices y TLOG
 Autor: Maximiliano Damian Accotto
 WWW.TRIGGERDB.COM
 BLOGS.TRIGGERDB.COM 

 Base de datos de ejemplo: StackOverflow2010 
 Link de descarga: https://downloads.brentozar.com/StackOverflow2010.7z
*/

---------------------------------------
----          Rebuild Index        ----     
---------------------------------------

USE [master]
GO

--------- RECOVERY MODE FULL -----------
USE [StackOverflow2010]
GO
DBCC SHRINKFILE (N'StackOverflow2010_log' , 256)
GO

ALTER DATABASE [StackOverflow2010] 
SET RECOVERY FULL WITH NO_WAIT
GO

USE StackOverflow2010 
GO

-- HACEMOS UN REBUILD INDEX
ALTER INDEX ALL ON [dbo].[Posts] REBUILD -- 5:10


SELECT T.TOTAL_LOG_SIZE_IN_BYTES / 1024 / 1024 
AS LOG_SIZE_MB,
T.USED_LOG_SPACE_IN_BYTES  / 1024 / 1024 AS LOG_USE_MB,
T.USED_LOG_SPACE_IN_PERCENT 
FROM  SYS.DM_DB_LOG_SPACE_USAGE T

--------- RECOVERY MODE SIMPLE -----------

ALTER DATABASE [StackOverflow2010] 
SET RECOVERY SIMPLE WITH NO_WAIT

USE [StackOverflow2010]
GO
DBCC SHRINKFILE (N'StackOverflow2010_log' , 256)
GO

ALTER INDEX ALL ON [dbo].[Posts] REBUILD 


SELECT T.TOTAL_LOG_SIZE_IN_BYTES / 1024 / 1024 
AS LOG_SIZE_MB,
T.USED_LOG_SPACE_IN_BYTES  / 1024 / 1024 AS LOG_USE_MB,
T.USED_LOG_SPACE_IN_PERCENT 
FROM  SYS.DM_DB_LOG_SPACE_USAGE T

-- HACEMOS EL SHRINK 

USE [StackOverflow2010]
GO
DBCC SHRINKFILE (N'StackOverflow2010_log' , 256)
GO


--------- RECOVERY MODE BULK_LOGGED  -----------

ALTER DATABASE [StackOverflow2010] 
SET RECOVERY BULK_LOGGED WITH NO_WAIT

ALTER INDEX ALL ON [dbo].[Posts] REBUILD 

SELECT T.TOTAL_LOG_SIZE_IN_BYTES / 1024 / 1024 
AS LOG_SIZE_MB,
T.USED_LOG_SPACE_IN_BYTES  / 1024 / 1024 AS LOG_USE_MB,
T.USED_LOG_SPACE_IN_PERCENT 
FROM  SYS.DM_DB_LOG_SPACE_USAGE T

---------------------------------------
----          ReORGANIZE Index        ----     
---------------------------------------

USE [StackOverflow2010]
GO
DBCC SHRINKFILE (N'StackOverflow2010_log' , 256)
GO


USE [master]
GO

--------- RECOVERY MODE FULL -----------


ALTER DATABASE [StackOverflow2010] 
SET RECOVERY FULL WITH NO_WAIT
GO

USE StackOverflow2010 
GO

-- HACEMOS UN REBUILD INDEX
ALTER INDEX ALL ON [dbo].[Posts] REORGANIZE


SELECT T.TOTAL_LOG_SIZE_IN_BYTES / 1024 / 1024 
AS LOG_SIZE_MB,
T.USED_LOG_SPACE_IN_BYTES  / 1024 / 1024 AS LOG_USE_MB,
T.USED_LOG_SPACE_IN_PERCENT 
FROM  SYS.DM_DB_LOG_SPACE_USAGE T

--------- RECOVERY MODE SIMPLE -----------

ALTER DATABASE [StackOverflow2010] 
SET RECOVERY SIMPLE WITH NO_WAIT

USE [StackOverflow2010]
GO
DBCC SHRINKFILE (N'StackOverflow2010_log' , 256)
GO

ALTER INDEX ALL ON [dbo].[Posts] REORGANIZE 


SELECT T.TOTAL_LOG_SIZE_IN_BYTES / 1024 / 1024 
AS LOG_SIZE_MB,
T.USED_LOG_SPACE_IN_BYTES  / 1024 / 1024 AS LOG_USE_MB,
T.USED_LOG_SPACE_IN_PERCENT 
FROM  SYS.DM_DB_LOG_SPACE_USAGE T

-- HACEMOS EL SHRINK 

USE [StackOverflow2010]
GO
DBCC SHRINKFILE (N'StackOverflow2010_log' , 256)
GO


--------- RECOVERY MODE BULK_LOGGED  -----------

ALTER DATABASE [StackOverflow2010] 
SET RECOVERY BULK_LOGGED WITH NO_WAIT

ALTER INDEX ALL ON [dbo].[Posts] REORGANIZE 

SELECT T.TOTAL_LOG_SIZE_IN_BYTES / 1024 / 1024 
AS LOG_SIZE_MB,
T.USED_LOG_SPACE_IN_BYTES  / 1024 / 1024 AS LOG_USE_MB,
T.USED_LOG_SPACE_IN_PERCENT 
FROM  SYS.DM_DB_LOG_SPACE_USAGE T





ALTER INDEX ALL ON [dbo].[Posts] REORGANIZE
