/*
 ALMACENAMIENTO DE IMAGENES EN SQL SERVER
 MAXIMILIANO ACCOTTO
 HTTPS://BLOGS.TRIGGERDB.COM
 WWW.TRIGGERDB.COM 
*/

---		VARBINARY

DROP DATABASE IF EXISTS TRIGGERDB  

CREATE DATABASE TRIGGERDB

USE TRIGGERDB 


DROP TABLE IF EXISTS DBO.DOCUMENTOS

CREATE TABLE DBO.DOCUMENTOS (ID INT IDENTITY,
                             NOMBRE VARCHAR(255),
                             CONTENIDO VARBINARY(MAX),
							 EXTENSION CHAR(4)
							 )
GO

INSERT INTO DBO.DOCUMENTOS (NOMBRE,CONTENIDO,EXTENSION)
SELECT 'LOGO-FONDO-BLANCO', BULKCOLUMN,'PNG'
FROM OPENROWSET(BULK N'E:\TMP\LOGO-FONDO-BLANCO.PNG', SINGLE_BLOB) AS DOCUMENT

INSERT INTO DBO.DOCUMENTOS (NOMBRE,CONTENIDO,EXTENSION)
SELECT 'LOGO-FONDO-VERDE', BULKCOLUMN,'PNG'
FROM OPENROWSET(BULK N'E:\TMP\LOGO-FONDO-VERDE.PNG', SINGLE_BLOB) AS DOCUMENT

SELECT * FROM DBO.DOCUMENTOS 

-------- FILESTREAM

EXEC sp_configure filestream_access_level, 2  
RECONFIGURE  

ALTER DATABASE [TRIGGERDB] 
ADD FILEGROUP [fs_imagenes] CONTAINS FILESTREAM 
GO

ALTER DATABASE [TRIGGERDB] 
ADD FILE ( NAME = N'triggerdb_fs', 
FILENAME = N'E:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\triggerdb_fs' ) TO FILEGROUP [fs_imagenes]



USE TRIGGERDB 
go

DROP TABLE IF EXISTS dbo.DOCUMENTOS_FS  

CREATE TABLE DBO.DOCUMENTOS_FS 
(ID INT IDENTITY,
 ID2 UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL UNIQUE,
 NOMBRE VARCHAR(255),
 CONTENIDO VARBINARY(MAX) FILESTREAM,
 EXTENSION CHAR(4)
)
GO


INSERT INTO DBO.DOCUMENTOS_FS (ID2,NOMBRE,CONTENIDO,EXTENSION)
SELECT NEWID(),'LOGO-FONDO-BLANCO', BULKCOLUMN,'PNG'
FROM OPENROWSET(BULK N'E:\TMP\LOGO-FONDO-BLANCO.PNG', SINGLE_BLOB) AS DOCUMENT

INSERT INTO DBO.DOCUMENTOS_FS (ID2,NOMBRE,CONTENIDO,EXTENSION)
SELECT NEWID(), 'LOGO-FONDO-VERDE', BULKCOLUMN,'PNG'
FROM OPENROWSET(BULK N'E:\TMP\LOGO-FONDO-VERDE.PNG', SINGLE_BLOB) AS DOCUMENT

SELECT * FROM DBO.DOCUMENTOS_FS


--- FileTable
USE [master]
GO
ALTER DATABASE 
[TRIGGERDB] 
SET FILESTREAM( DIRECTORY_NAME = N'Triggerdb' ) WITH 
rollback immediate 
GO

USE [master]
GO
ALTER DATABASE [TRIGGERDB] 
SET FILESTREAM( NON_TRANSACTED_ACCESS = FULL, 
DIRECTORY_NAME = N'Triggerdb' ) WITH 
rollback immediate 
GO


use TRIGGERDB 

drop table if exists MyDocumentStore

CREATE TABLE MyDocumentStore AS FileTable
WITH
(
    FileTable_Directory = 'MyDocumentStore',
    FileTable_Collate_Filename = database_default,
	FILETABLE_STREAMID_UNIQUE_CONSTRAINT_NAME=UQ_stream_id);
GO



